module.exports = [ 
    '@ireaderinokun',
    '@timigod',
    '@twisted_myk',
    '@robertjgabriel',
    '@fathermerry',
    '@seyitaylor',
    '@ienoobong',
    '@theLiveware',
    '@efemoney_',
    '@udezekene',
    '@abahnj',
    '@ribads',
    '@Ope__O',
    '@emma_odia',
    '@victorbolum',
    '@frontenderic',
    '@perfectmak'
    '@_Folz'
];
